import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('limsApi', {
  dashboard: () => ipcRenderer.invoke('dashboard'),
  getSettings: () => ipcRenderer.invoke('settings:get-all'),
  saveSettings: (s: any) => ipcRenderer.invoke('settings:save-all', s),
  getSetting: (key: string, fallback = '') => ipcRenderer.invoke('settings:get-one', key, fallback),
  setSetting: (key: string, value: string) => ipcRenderer.invoke('settings:set-one', key, value),
  chooseReportBackgroundImage: () => ipcRenderer.invoke('report:choose-image'),
  listDepartments: () => ipcRenderer.invoke('masters:departments'),
  saveDepartment: (x: any) => ipcRenderer.invoke('masters:department:save', x),
  reorderDepartments: (items: any[]) => ipcRenderer.invoke('masters:departments:reorder', items),
  listUnits: () => ipcRenderer.invoke('masters:units'),
  saveUnit: (x: any) => ipcRenderer.invoke('masters:unit:save', x),
  listTests: (activeOnly?: boolean) => ipcRenderer.invoke('masters:tests', activeOnly),
  saveTest: (x: any) => ipcRenderer.invoke('masters:test:save', x),
  deleteTest: (id: number) => ipcRenderer.invoke('masters:test:delete', id),
  reorderTests: (items: any[]) => ipcRenderer.invoke('masters:tests:reorder', items),
  listSpecimens: () => ipcRenderer.invoke('masters:specimens'),
  saveSpecimen: (x: any) => ipcRenderer.invoke('masters:specimen:save', x),
  listMethods: () => ipcRenderer.invoke('masters:methods'),
  listProfiles: (activeOnly?: boolean) => ipcRenderer.invoke('masters:profiles', activeOnly),
  saveProfile: (x: any) => ipcRenderer.invoke('masters:profile:save', x),
  reorderProfiles: (items: any[]) => ipcRenderer.invoke('masters:profiles:reorder', items),
  deleteProfile: (id: number) => ipcRenderer.invoke('masters:profile:delete', id),
  listEquipment: (activeOnly?: boolean) => ipcRenderer.invoke('masters:equipment:list', activeOnly),
  saveEquipment: (x: any) => ipcRenderer.invoke('masters:equipment:save', x),
  deleteEquipment: (id: number) => ipcRenderer.invoke('masters:equipment:delete', id),
  listConsultants: () => ipcRenderer.invoke('consultants:list'),
  saveConsultant: (x: any) => ipcRenderer.invoke('consultants:save', x),
  deleteConsultant: (id: number) => ipcRenderer.invoke('consultants:delete', id),
  calculateCommission: (payload: any) => ipcRenderer.invoke('consultants:commission:calculate', payload),
  listCommissions: (filters?: any) => ipcRenderer.invoke('commissions:list', filters || {}),
  updateCommissionStatus: (payload: any) => ipcRenderer.invoke('commissions:status', payload),
  settleCommissions: (payload: any) => ipcRenderer.invoke('commissions:settle', payload),
  listCommissionSettlements: (filters?: any) => ipcRenderer.invoke('commissions:settlements', filters || {}),
  listCommissionGroups: () => ipcRenderer.invoke('commissions:groups:list'),
  saveCommissionGroup: (payload:any) => ipcRenderer.invoke('commissions:groups:save', payload||{}),
  deleteCommissionGroup: (id:number) => ipcRenderer.invoke('commissions:groups:delete', id),
  validateCommissionFormula: (payload:any) => ipcRenderer.invoke('commissions:formula:validate', payload||{}),
  listConsultantCommissionGroups: (consultantId:number) => ipcRenderer.invoke('commissions:consultant-groups:list', consultantId),
  saveConsultantCommissionGroups: (payload:any) => ipcRenderer.invoke('commissions:consultant-groups:save', payload||{}),

  operationsDashboard: () => ipcRenderer.invoke('operations:dashboard'),
  listVendors: () => ipcRenderer.invoke('operations:vendors:list'),
  saveVendor: (x: any) => ipcRenderer.invoke('operations:vendors:save', x),
  listInventoryItems: () => ipcRenderer.invoke('operations:inventory:list'),
  listOperationUnits: () => ipcRenderer.invoke('operations:units:list'),
  listOperationBrands: () => ipcRenderer.invoke('operations:brands:list'),
  listOperationHsns: () => ipcRenderer.invoke('operations:hsns:list'),
  listInventoryItemVersions: (itemId: number) => ipcRenderer.invoke('operations:inventory:versions', itemId),
  listInventoryBatches: (itemId: number) => ipcRenderer.invoke('operations:inventory:batches', itemId),
  saveInventoryItem: (x: any) => ipcRenderer.invoke('operations:inventory:save', x),
  savePurchase: (x: any) => ipcRenderer.invoke('operations:purchases:save', x),
  listPurchases: (f?: any) => ipcRenderer.invoke('operations:purchases:list', f),
  listPurchaseItemHistory: (itemId: number) => ipcRenderer.invoke('operations:purchases:item-history', itemId),
  listReagentConsumption: (testId?: number) => ipcRenderer.invoke('operations:reagents:list', testId),
  saveReagentConsumption: (x: any) => ipcRenderer.invoke('operations:reagents:save', x),
  deleteReagentConsumption: (id: number) => ipcRenderer.invoke('operations:reagents:delete', id),
  saveExpense: (x: any) => ipcRenderer.invoke('operations:expenses:save', x),
  listExpenses: (f?: any) => ipcRenderer.invoke('operations:expenses:list', f),
  savePayment: (x: any) => ipcRenderer.invoke('operations:payments:save', x),
  listPayments: (f?: any) => ipcRenderer.invoke('operations:payments:list', f),
  listOutsourceVendors: () => ipcRenderer.invoke('operations:outsource-vendors:list'),
  saveOutsourceVendor: (x: any) => ipcRenderer.invoke('operations:outsource-vendors:save', x),
  listOutsourceRates: () => ipcRenderer.invoke('operations:outsource-rates:list'),
  saveOutsourceRate: (x: any) => ipcRenderer.invoke('operations:outsource-rates:save', x),
  saveOutsourceCase: (x: any) => ipcRenderer.invoke('operations:outsource-cases:save', x),
  listOutsourceCases: (f?: any) => ipcRenderer.invoke('operations:outsource-cases:list', f),

  listCollectionPending: () => ipcRenderer.invoke('collection:pending'),
  listAcceptedCollectionPending: () => ipcRenderer.invoke('collection:accepted-pending'),
  acceptCollectionRequest: (billId: number) => ipcRenderer.invoke('collection:accept-request', billId),
  cancelAcceptedCollectionRequest: (billId: number) => ipcRenderer.invoke('collection:cancel-accepted-request', billId),
  getCollectionBill: (billId: number) => ipcRenderer.invoke('collection:bill', billId),
  saveCollection: (payload: any) => ipcRenderer.invoke('collection:save', payload),
  listCollections: (f?: any) => ipcRenderer.invoke('collection:list', f),
  listCollectionLogs: (f?: any) => ipcRenderer.invoke('collection:logs', f),
  updateCollectionDispatchStatus: (collectionId: number, status: string) => ipcRenderer.invoke('collection:dispatch-status', collectionId, status),
  receiveOutsourceVendorResult: (collectionId: number, payload: any) => ipcRenderer.invoke('collection:vendor-result', collectionId, payload),
  rejectCollection: (collectionId: number, reason: string) => ipcRenderer.invoke('collection:reject', collectionId, reason),
  deleteRejectedCollection: (collectionId: number) => ipcRenderer.invoke('collection:delete-rejected', collectionId),
  recollectCollection: (collectionId: number) => ipcRenderer.invoke('collection:recollect', collectionId),
  reopenApprovedReportFromCollection: (ref: any, reason: string) => ipcRenderer.invoke('collection:reopen-approved-report', ref, reason),
  listPatients: (q?: string) => ipcRenderer.invoke('patients:list', q),
  savePatient: (x: any) => ipcRenderer.invoke('patients:save', x),
  patientHistory: (id: number) => ipcRenderer.invoke('patients:history', id),
  previewUnusedPatients: () => ipcRenderer.invoke('patients:unused-preview'),
  dropUnusedPatients: () => ipcRenderer.invoke('patients:drop-unused'),
  createBill: (payload: any) => ipcRenderer.invoke('billing:create', payload),
  updateBill: (payload: any) => ipcRenderer.invoke('billing:update', payload),
  listBills: (filters?: any) => ipcRenderer.invoke('billing:list', filters),
  analytics: (filters?: any) => ipcRenderer.invoke('billing:analytics', filters),
  getBill: (id: number) => ipcRenderer.invoke('billing:get', id),
  cancelBill: (billId: number, payload: any) => ipcRenderer.invoke('billing:cancel', billId, payload),
  deleteBill: (billId: number) => ipcRenderer.invoke('billing:delete', billId),
  addReceipt: (billId: number, amount: number, mode: string) => ipcRenderer.invoke('receipts:add', billId, amount, mode),
  deleteReceipt: (billId: number, receiptId: number) => ipcRenderer.invoke('receipts:delete', billId, receiptId),
  listReports: (status?: string) => ipcRenderer.invoke('reports:list', status),
  listReportLogs: (f?: any) => ipcRenderer.invoke('reports:logs', f),
  getReport: (id: number) => ipcRenderer.invoke('reports:get', id),
  saveReport: (payload: any) => ipcRenderer.invoke('reports:save', payload),
  removePendingReport: (reportId: number, payload?: any) => ipcRenderer.invoke('reports:remove-pending', reportId, payload || {}),
  rejectReport: (reportId: number, payload: any) => ipcRenderer.invoke('reports:reject', reportId, payload),
  reopenApprovedReportForCorrection: (reportId: number, payload: any) => ipcRenderer.invoke('reports:reopen-approved-correction', reportId, payload),
  requestReportRecheck: (payload: any) => ipcRenderer.invoke('reports:request-recheck', payload),
  revertReportRecheck: (payload: any) => ipcRenderer.invoke('reports:revert-recheck', payload),
  quickCancelReport: (reportId: number, reason?: string) => ipcRenderer.invoke('reports:quick-cancel', reportId, reason || 'Cancelled from Finished Reports'),
  quickDeleteReport: (reportId: number, reason?: string) => ipcRenderer.invoke('reports:quick-delete', reportId, reason || 'Deleted from Finished Reports'),
  quickBarcodeState: (reportOrBillId: number) => ipcRenderer.invoke('quick-reporting-barcode:state', reportOrBillId),
  quickBarcodeGenerate: (reportOrBillId: number, payload: any) => ipcRenderer.invoke('quick-reporting-barcode:generate', reportOrBillId, payload || {}),
  quickBarcodeReset: (reportOrBillId: number, payload: any) => ipcRenderer.invoke('quick-reporting-barcode:reset', reportOrBillId, payload || {}),
  reportPdf: (id: number, withBackground?: boolean) => ipcRenderer.invoke('reports:pdf', id, withBackground),
  reportPdfData: (id: number, withBackground?: boolean) => ipcRenderer.invoke('reports:pdf-data', id, withBackground),
  reportSettingsPreviewPdfData: (mode?: 'profile' | 'single', withBackground?: boolean) => ipcRenderer.invoke('reports:settings-preview-pdf-data', mode, withBackground),
  reportExcel: (id: number) => ipcRenderer.invoke('reports:excel', id),
  printReport: (id: number, withBackground?: boolean) => ipcRenderer.invoke('reports:print', id, withBackground),
  htmlToPdfOpen: (payload: any) => ipcRenderer.invoke('print:html-pdf-open', payload || {}),
  analyticsPdfOpen: (payload: any) => ipcRenderer.invoke('analytics:pdf-open', payload || {}),
  analyticsXlsxOpen: (payload: any) => ipcRenderer.invoke('analytics:xlsx-open', payload || {}),
  approvedReportPdfExport: (id: number, options?: any) => ipcRenderer.invoke('reports:approved-pdf-export', id, options),
  approvedReportPrint: (id: number, options?: any) => ipcRenderer.invoke('reports:approved-print', id, options),
  approvedReportEmail: (id: number, options?: any) => ipcRenderer.invoke('reports:approved-email', id, options),
  approvedReportWhatsapp: (id: number, options?: any) => ipcRenderer.invoke('reports:approved-whatsapp', id, options),
  openWhatsAppContact: (mobile: string) => ipcRenderer.invoke('whatsapp:open-contact', mobile),
  approvedReportSms: (id: number, options?: any) => ipcRenderer.invoke('reports:approved-sms', id, options),
  reportItemHistory: (patientId: number, testId: number, currentReportId?: number) => ipcRenderer.invoke('reports:item-history', patientId, testId, currentReportId),
  billPdf: (billId: number, includeReceipts?: boolean) => ipcRenderer.invoke('billing:pdf', billId, includeReceipts),
  receiptPdf: (billId: number, receiptId?: number) => ipcRenderer.invoke('receipts:pdf', billId, receiptId),
  statement: (filters?: any) => ipcRenderer.invoke('statement', filters),
  statementExcel: (filters?: any) => ipcRenderer.invoke('statement:excel', filters),
  statementPdf: (filters?: any) => ipcRenderer.invoke('statement:pdf', filters),
  createBackup: (reason?: string) => ipcRenderer.invoke('backup:create', reason),
  listBackups: () => ipcRenderer.invoke('backup:list'),
  validateBackup: (filePath: string) => ipcRenderer.invoke('backup:validate', filePath),
  restoreBackup: (filePath: string) => ipcRenderer.invoke('backup:restore', filePath),
  resetWorkflowData: () => ipcRenderer.invoke('debug:reset-workflow-data'),
  getDataDir: () => ipcRenderer.invoke('paths:data-dir'),
  getReportsDir: () => ipcRenderer.invoke('paths:reports-dir'),
  chooseDirectory: (title?: string) => ipcRenderer.invoke('paths:choose-dir', title),
  setDataDir: (dir: string) => ipcRenderer.invoke('paths:set-data-dir', dir),
  openPath: (p: string) => ipcRenderer.invoke('paths:open', p),
  analyzerApiStatus: () => ipcRenderer.invoke('analyzer-api:status'),
  restartAnalyzerApi: () => ipcRenderer.invoke('analyzer-api:restart'),
  setDirty: (dirty: boolean) => ipcRenderer.invoke('app:set-dirty', dirty),
  onReportProgress: (callback: (progress:any) => void) => {
    const listener = (_event:any, progress:any) => callback(progress);
    ipcRenderer.on('report-progress', listener);
    return () => ipcRenderer.removeListener('report-progress', listener);
  },
  onCloseRequest: (callback: () => void) => {
    const listener = () => callback();
    ipcRenderer.on('app:close-request', listener);
    return () => ipcRenderer.removeListener('app:close-request', listener);
  },
  onAlreadyRunning: (callback: (payload?: { title?: string; message?: string; details?: string }) => void) => {
    const listener = (_event: any, payload?: { title?: string; message?: string; details?: string }) => callback(payload);
    ipcRenderer.on('app:already-running', listener);
    return () => ipcRenderer.removeListener('app:already-running', listener);
  },
  onShutdownProgress: (callback: (progress: any) => void) => {
    const listener = (_event: any, progress: any) => callback(progress);
    ipcRenderer.on('app:shutdown-progress', listener);
    return () => ipcRenderer.removeListener('app:shutdown-progress', listener);
  },
  prepareShutdown: () => ipcRenderer.invoke('app:prepare-shutdown'),
  closeDecision: (allowClose: boolean) => ipcRenderer.invoke('app:close-decision', allowClose)
});
