export interface LimsApi {
  dashboard(): Promise<any>;
  getSettings(): Promise<Record<string, string>>;
  saveSettings(settings: Record<string, any>): Promise<Record<string, string>>;
  getSetting?(key: string, fallback?: string): Promise<string>;
  setSetting?(key: string, value: string): Promise<any>;
  chooseReportBackgroundImage?(): Promise<{path: string} | null>;
  listDepartments(): Promise<any[]>;
  saveDepartment(item: any): Promise<any[]>;
  reorderDepartments?(items: any[]): Promise<any[]>;
  listUnits(): Promise<any[]>;
  saveUnit(item: any): Promise<any[]>;
  listTests(activeOnly?: boolean): Promise<any[]>;
  saveTest(item: any): Promise<any[]>;
  deleteTest?(id: number): Promise<any[]>;
  reorderTests?(items: any[]): Promise<any[]>;
  listSpecimens(): Promise<any[]>;
  saveSpecimen(item: any): Promise<any[]>;
  listMethods(): Promise<any[]>;
  listProfiles(activeOnly?: boolean): Promise<any[]>;
  saveProfile(item: any): Promise<any[]>;
  reorderProfiles?(items: any[]): Promise<any[]>;
  deleteProfile?(id: number): Promise<any[]>;
  listEquipment?(activeOnly?: boolean): Promise<any[]>;
  saveEquipment?(item: any): Promise<any[]>;
  deleteEquipment?(id: number): Promise<any[]>;
  listConsultants(): Promise<any[]>;
  saveConsultant(item: any): Promise<any[]>;
  deleteConsultant?(id: number): Promise<{action: string; consultants: any[]}>;
  calculateCommission?(payload: any): Promise<any>;
  listCommissions?(filters?: any): Promise<{rows:any[]; totals:any}>;
  updateCommissionStatus?(payload: any): Promise<any>;
  settleCommissions?(payload: any): Promise<any>;
  listCommissionSettlements?(filters?: any): Promise<any[]>;
  listCommissionGroups?(): Promise<any[]>;
  saveCommissionGroup?(payload:any): Promise<any>;
  deleteCommissionGroup?(id:number): Promise<any[]>;
  validateCommissionFormula?(payload:any): Promise<any>;
  listConsultantCommissionGroups?(consultantId:number): Promise<any[]>;
  saveConsultantCommissionGroups?(payload:any): Promise<any[]>;
  operationsDashboard?(): Promise<any>;
  listVendors?(): Promise<any[]>;
  saveVendor?(item: any): Promise<any[]>;
  listInventoryItems?(): Promise<any[]>;
  listOperationUnits?(): Promise<any[]>;
  listOperationBrands?(): Promise<any[]>;
  listOperationHsns?(): Promise<any[]>;
  listInventoryItemVersions?(itemId: number): Promise<any[]>;
  listInventoryBatches?(itemId: number): Promise<any[]>;
  saveInventoryItem?(item: any): Promise<any[]>;
  savePurchase?(payload: any): Promise<any>;
  listPurchases?(filters?: any): Promise<any[]>;
  listPurchaseItemHistory?(itemId: number): Promise<any[]>;
  listReagentConsumption?(testId?: number): Promise<any[]>;
  saveReagentConsumption?(item: any): Promise<any[]>;
  deleteReagentConsumption?(id: number): Promise<any[]>;
  saveExpense?(item: any): Promise<any[]>;
  listExpenses?(filters?: any): Promise<any[]>;
  savePayment?(item: any): Promise<any[]>;
  listPayments?(filters?: any): Promise<any[]>;
  listOutsourceVendors?(): Promise<any[]>;
  saveOutsourceVendor?(item: any): Promise<any[]>;
  listOutsourceRates?(): Promise<any[]>;
  saveOutsourceRate?(item: any): Promise<any[]>;
  saveOutsourceCase?(item: any): Promise<any[]>;
  listOutsourceCases?(filters?: any): Promise<any[]>;

  listCollectionPending?(): Promise<any[]>;
  listAcceptedCollectionPending?(): Promise<any[]>;
  acceptCollectionRequest?(billId: number): Promise<any>;
  cancelAcceptedCollectionRequest?(billId: number): Promise<any>;
  getCollectionBill?(billId: number): Promise<any>;
  saveCollection?(payload: any): Promise<any>;
  listCollections?(filters?: any): Promise<any[]>;
  listCollectionLogs?(filters?: any): Promise<any[]>;
  updateCollectionDispatchStatus?(collectionId: number, status: string): Promise<any>;
  receiveOutsourceVendorResult?(collectionId: number, payload: any): Promise<any>;
  rejectCollection?(collectionId: number, reason: string): Promise<any>;
  deleteRejectedCollection?(collectionId: number): Promise<any>;
  recollectCollection?(collectionId: number): Promise<any>;
  reopenApprovedReportFromCollection?(ref: any, reason: string): Promise<any>;
  listPatients(q?: string): Promise<any[]>;
  savePatient(item: any): Promise<number>;
  patientHistory(id: number): Promise<any>;
  previewUnusedPatients?(): Promise<{ count: number; totalPatients: number; sample: any[] }>;
  dropUnusedPatients?(): Promise<{ ok: boolean; deleted: number; totalPatients: number }>;
  createBill(payload: any): Promise<any>;
  updateBill(payload: any): Promise<any>;
  listBills(filters?: any): Promise<any[]>;
  analytics?(filters?: any): Promise<any>;
  analyticsPdfOpen?(payload: any): Promise<string>;
  analyticsXlsxOpen?(payload: any): Promise<string>;
  getBill(id: number): Promise<any>;
  cancelBill?(billId: number, payload: any): Promise<any>;
  deleteBill?(billId: number): Promise<any>;
  addReceipt(billId: number, amount: number, mode: string): Promise<string>;
  deleteReceipt?(billId: number, receiptId: number): Promise<any>;
  listReports(status?: string): Promise<any[]>;
  listReportLogs?(filters?: any): Promise<any[]>;
  getReport(id: number): Promise<any>;
  saveReport(payload: any): Promise<any>;
  removePendingReport?(reportId: number, payload?: any): Promise<any>;
  rejectReport?(reportId: number, payload: any): Promise<any>;
  reopenApprovedReportForCorrection?(reportId: number, payload: any): Promise<any>;
  requestReportRecheck?(payload: any): Promise<any>;
  revertReportRecheck?(payload: any): Promise<any>;
  quickCancelReport?(reportId: number, reason?: string): Promise<any>;
  quickDeleteReport?(reportId: number, reason?: string): Promise<any>;
  reportPdf(id: number, withBackground?: boolean): Promise<string>;
  reportPdfData?(id: number, withBackground?: boolean): Promise<{file: string; dataUrl: string}>;
  reportExcel(id: number): Promise<string>;
  printReport(id: number, withBackground?: boolean): Promise<string>;
  onReportProgress?(callback: (progress:any) => void): () => void;
  approvedReportPdfExport?(id: number, options?: any): Promise<string>;
  approvedReportPrint?(id: number, options?: any): Promise<string>;
  approvedReportEmail?(id: number, options?: any): Promise<any>;
  approvedReportWhatsapp?(id: number, options?: any): Promise<any>;
  openWhatsAppContact?(mobile: string): Promise<{ ok: boolean; mobile: string }>;
  approvedReportSms?(id: number, options?: any): Promise<any>;
  reportItemHistory?(patientId: number, testId: number, currentReportId?: number): Promise<any[]>;
  billPdf(billId: number, includeReceipts?: boolean): Promise<string>;
  receiptPdf(billId: number, receiptId?: number): Promise<string>;
  statement(filters?: any): Promise<any>;
  statementExcel(filters?: any): Promise<string>;
  statementPdf(filters?: any): Promise<string>;
  createBackup(reason?: string): Promise<any>;
  listBackups(): Promise<any[]>;
  validateBackup(filePath: string): Promise<any>;
  restoreBackup(filePath: string): Promise<any>;
  resetWorkflowData?(): Promise<any>;
  getDataDir(): Promise<string>;
  getReportsDir(): Promise<string>;
  chooseDirectory?(title?: string): Promise<{path: string} | null>;
  setDataDir?(dir: string): Promise<{dataDir: string; restartRequired: boolean; copied?: boolean; usedExisting?: boolean; message?: string}>;
  openPath(path: string): Promise<string>;
  analyzerApiStatus?(): Promise<any>;
  restartAnalyzerApi?(): Promise<any>;
  setDirty?(dirty: boolean): Promise<boolean>;
  onCloseRequest?(callback: () => void): () => void;
  onAlreadyRunning?(callback: (payload?: { title?: string; message?: string; details?: string }) => void): () => void;
  onShutdownProgress?(callback: (progress: any) => void): () => void;
  prepareShutdown?(): Promise<any>;
  closeDecision?(allowClose: boolean): Promise<void>;
}

declare global {
  interface Window { limsApi: LimsApi; }
}
